sequenceDiagram
    actor User
    participant AuthenticatedUser
    participant ShoppingStore
    participant Item
    participant Cart
    User->>+AuthenticatedUser: click addtocart
    AuthenticatedUser->>+Item: create item (Product,number)
    Item-->>-AuthenticatedUser: Item
    AuthenticatedUser->>+Cart:add_to_cart(Item)
    Cart-->>-AuthenticatedUser:ok
    AuthenticatedUser-->>User: ok