sequenceDiagram
    actor User
    participant MeetingScheduler
    participant MeetingRoom
    participant Interval
    User->>+MeetingScheduler: get_available_room(d1,t1,d2,t2)
    loop
        MeetingScheduler->>+MeetingRoom: is_available()
        MeetingRoom-->>-MeetingScheduler: Y or N
        MeetingScheduler->>+MeetingRoom: check_capacity(n)
        MeetingRoom-->>-MeetingScheduler: Y or N
        MeetingScheduler->>+MeetingRoom: room_available(d1,t1,d2,t2)
        loop
            MeetingRoom->>+Interval:get_start_end_time()
            Interval-->>-MeetingRoom:start_time,end_time
            MeetingRoom->>MeetingRoom:check_no_overlap
        end
        MeetingRoom-->>-MeetingScheduler: Y or N
    end
    MeetingScheduler-->>-User: list of available room